// Test file to manually test SMS functionality
const { sendSMS } = require('./utils/sms');

async function testSMS() {
    console.log('🧪 Testing Africa\'s Talking SMS API...\n');
    
    // Test phone number (replace with your actual number for testing)
    const testPhoneNumber = '+2348082225459';
    
    // Sample SMS message (like the one generated by the app)
    const testMessage = `Acct:227****865
DT:28/07/2025 09:04:28 PM
CIP/CR//Transfer from BABATUNDE
CR Amt:4,000.00
Bal:3,655.19
Dial *966# for quick airtime/Data purchase`;

    try {
        const result = await sendSMS(testPhoneNumber, testMessage);
        
        if (result.success) {
            console.log('🎉 SMS Test PASSED!');
            console.log('📱 Message ID:', result.messageId);
            console.log('💰 Cost:', result.cost);
        } else {
            console.log('❌ SMS Test FAILED!');
            console.log('❌ Error:', result.error);
        }
        
    } catch (error) {
        console.error('💥 Test crashed:', error);
    }
}

// Run the test
testSMS();

// Example usage as requested:
// sendSMS("+2348082225459", "Hello Sandbox SMS!");

// Uncomment below to test the example:
// sendSMS("+2348082225459", "Hello Sandbox SMS!")
//     .then(result => console.log('Example result:', result))
//     .catch(error => console.error('Example error:', error));